# Generated by Django 3.0.4 on 2020-03-14 10:03

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=50)),
                ('user_country', models.BigIntegerField()),
                ('user_mail', models.CharField(max_length=100, unique=True)),
                ('user_phoneno', models.CharField(max_length=15, unique=True)),
                ('usertype', models.BigIntegerField()),
                ('user_location', models.TextField()),
                ('company_name', models.CharField(max_length=20)),
                ('user_otp', models.CharField(max_length=6, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'UserRegistration',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_holder_name', models.CharField(max_length=30)),
                ('type_account', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('account_no', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=20)),
                ('transfer_type', models.CharField(max_length=20)),
                ('swift_code', models.CharField(max_length=25)),
                ('micr_no', models.CharField(max_length=25)),
                ('iban_code', models.CharField(max_length=25)),
                ('created_by_id', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'BankDetails',
            },
        ),
        migrations.CreateModel(
            name='CommunicationDetailsCompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('country', models.BigIntegerField()),
                ('state', models.BigIntegerField()),
                ('city', models.BigIntegerField()),
                ('pincode', models.CharField(max_length=10)),
                ('landmark', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=20)),
                ('mail_id', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'CommunicationDetailsCompanyAddress',
            },
        ),
        migrations.CreateModel(
            name='CommunicationDetailsShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_company_name', models.CharField(max_length=50)),
                ('shipping_country', models.BigIntegerField()),
                ('shipping_state', models.BigIntegerField()),
                ('shipping_city', models.BigIntegerField()),
                ('shipping_pincode', models.CharField(max_length=10)),
                ('shipping_landmark', models.CharField(max_length=50)),
                ('shipping_address', models.CharField(max_length=100)),
                ('shipping_mail_id', models.CharField(max_length=50)),
                ('shipping_telephone', models.CharField(max_length=15)),
                ('shipping_mobile', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'CommunicationDetailsShippingAddress',
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dept', models.BigIntegerField()),
                ('designation', models.BigIntegerField()),
                ('contact_no', models.CharField(max_length=15)),
                ('mobile_no', models.CharField(max_length=15)),
                ('mail_id', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Contact_Details',
            },
        ),
        migrations.CreateModel(
            name='LegalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=20)),
                ('registered_date', models.DateField()),
                ('valid_till', models.DateField()),
                ('upload_document', models.FileField(upload_to='')),
                ('document', models.BinaryField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LegalInformation',
            },
        ),
        migrations.CreateModel(
            name='BasiCompanyInfo',
            fields=[
                ('basic_company_info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_type', models.BigIntegerField()),
                ('tax_payer_type', models.BigIntegerField()),
                ('registration_date', models.DateTimeField()),
                ('buziness_country', models.BigIntegerField()),
                ('buziness_currency', models.BigIntegerField()),
                ('buziness_type', models.CharField(max_length=20)),
                ('msme_registered', models.BooleanField()),
                ('gst_no', models.CharField(max_length=20)),
                ('pan_no', models.CharField(max_length=10)),
                ('nature_of_buziness', models.BigIntegerField()),
                ('created_by_id', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by_id', models.BigIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BasiCompanyInfo',
            },
        ),
    ]
