# Generated by Django 3.0.4 on 2020-03-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorsindmsapp', '0003_remove_userregistration_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='user_country',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='usertype',
            field=models.BigIntegerField(null=True),
        ),
    ]
